name: Windows (Client-only, Release)

# This is derived from the standard CMake template for github actions.
# For more details on the settings used, have a look at the template in the marketplace

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Fetch submodules
      # Recursively checkout submodules
      # TODO Violin use shallow clone to save resources
      run: |
        git submodule update --init --recursive

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      # Build only a minimal (client-only) version on Windows to save resources
      run: |
        cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
            -Dramses-sdk_BUILD_EXAMPLES=OFF \
            -Dramses-sdk_BUILD_SMOKE_TESTS=OFF \
            -Dramses-sdk_BUILD_DEMOS=OFF \
            -Dramses-sdk_BUILD_CLIENT_ONLY_SHARED_LIB=ON \
            -Dramses-sdk_BUILD_FULL_SHARED_LIB=OFF

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

    - name: Test
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: ctest -C $BUILD_TYPE

